In [4]:
import tensorflow as tf
sess = tf.Session()

In [29]:
ph    = tf.placeholder(shape=[3,3],       dtype=tf.float32)
var   = tf.Variable([1, 2, 3, 4, 5],      dtype=tf.float32)
const = tf.constant([10, 20, 30, 40, 50], dtype=tf.float32)

In [10]:
##### Constant #####

a = tf.constant([5])
b = tf.constant([10])
c = tf.constant([2])

d = a * b + c

result = sess.run(d)
print(result)


In [20]:
##### Varible #####
# Variable은 반드시 초기화를 시켜줘야 하는 Tensor
#      : Weight, Bias 처럼 초기화 및 수정을 진행하는 변수 지정

var1 = tf.Variable( [5] ) # dtype 지정가능
var2 = tf.Variable( [3] ) # dtype 지정가능
var3 = tf.Variable( [2] ) # dtype 지정가능

var4 = var1 * var2 + var3
print(var4, '\n')

##### Variable 초기화
init = tf.initialize_all_variables()
sess.run( init )

result = sess.run( var4 )
print(result)

Tensor("add_5:0", shape=(1,), dtype=int32) 

[17]


In [21]:
##### Placeholder #####
# Placeholder는 mapping chart이며 feed_dict으로 mapping 시켜줘야 실행가능
#    : Tensorflow 외의 자료형 데이터를 TF로 들여오는 경우에 주로 사용

value1 = 5
value2 = 3
value3 = 2

ph1 = tf.placeholder( dtype=tf.float32 ) # Shape 지정가능
ph2 = tf.placeholder( dtype=tf.float32 ) # Shape 지정가능
ph3 = tf.placeholder( dtype=tf.float32 ) # Shape 지정가능

result_value = ph1 * ph2 + ph3

# feed 딕셔너리 생성 (Mapping)
feed_dict = {ph1: value1, ph2: value2, ph3: value3}

result = sess.run(result_value, feed_dict=feed_dict)
print(result)

17.0


In [28]:
# Placeholder 기반 image 매트릭스 Mapping

image = [[1, 2, 3, 4, 5],
         [5, 4, 3, 2, 1],
         [10, 20, 30, 40, 50]]
label = [10, 20, 30, 40, 50]

ph_image = tf.placeholder( dtype=tf.float32 )
ph_label = tf.placeholder( dtype=tf.float32 )

feed_dict = { ph_image: image, ph_label: label }

result_tensor = ph_image + ph_label
result = sess.run(result_tensor, feed_dict=feed_dict)
print(result)

[[ 11.  22.  33.  44.  55.]
 [ 15.  24.  33.  42.  51.]
 [ 20.  40.  60.  80. 100.]]
