In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]

In [3]:
arr1 = np.array(data1)

In [4]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
arr1.shape

(5,)

In [6]:
data2 = [[1,2,3,4],
         [5,6,7,8]]

In [7]:
arr2 = np.array(data2)

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.shape

(2, 4)

In [11]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int32')

In [19]:
arr = np.array([1,2,3,4,5], dtype=np.int64)

In [20]:
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [21]:
arr.dtype

dtype('int64')

In [22]:
float_arr = arr.astype(np.float64)

In [23]:
float_arr

array([1., 2., 3., 4., 5.])

In [24]:
float_arr.dtype

dtype('float64')

In [25]:
arr1 = np.array([[1,2,3],[4,5,6]], dtype = np.float64)
arr2 = np.array([[7,8,9],[10,11,12]], dtype = np.float64)

In [26]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [27]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [33]:
print(arr1 + arr2, '\n')
print(arr1 - arr2, '\n')
print(arr1 * arr2, '\n')
print(arr1 / arr2, '\n')
print(arr1 ** arr2, '\n')

[[ 8. 10. 12.]
 [14. 16. 18.]] 

[[-6. -6. -6.]
 [-6. -6. -6.]] 

[[ 7. 16. 27.]
 [40. 55. 72.]] 

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]] 

[[1.00000000e+00 2.56000000e+02 1.96830000e+04]
 [1.04857600e+06 4.88281250e+07 2.17678234e+09]] 



In [35]:
arr1 ** 0.5
arr1 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])