In [1]:
import numpy as np

# 1차원 array 인덱싱

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5]

5

In [4]:
arr[5:8]

array([5, 6, 7])

In [5]:
arr[5:8] = 12

In [6]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [7]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

# 2차원 array 인덱싱

In [9]:
arr2d = np.array([[1,  2,  3,  4 ],
                  [5,  6,  7,  8 ],
                  [9,  10, 11, 12],
                  [13, 14, 15, 16]])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
arr2d[2, :]

array([ 9, 10, 11, 12])

In [13]:
arr2d[1:3, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr2d[:, :2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [18]:
arr2d[:2, 1:3] = 0

In [19]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# 마스크를 이용한 인덱싱

In [46]:
names = np.array(["Charles", "Kilho", "Hayoung", "Charles", "Hayoung", "Kilho", "Kilho"])
data  = np.random.randn(7,4)

In [47]:
names

array(['Charles', 'Kilho', 'Hayoung', 'Charles', 'Hayoung', 'Kilho',
       'Kilho'], dtype='<U7')

In [48]:
data

array([[ 1.74380953,  0.41075475, -0.36585318,  0.61616358],
       [ 0.33475303, -0.22886941, -1.97264993, -1.32430933],
       [-1.7020177 , -0.09785498, -1.79617633, -0.97749358],
       [ 2.14664601, -0.4652285 , -1.09416193, -0.52367773],
       [-1.01999619, -0.59397758,  0.25072865, -0.57015537],
       [-0.10149452, -0.80051021,  0.96158134,  2.46254377],
       [ 1.83083561,  0.17823193, -0.07065599,  0.6681713 ]])

In [49]:
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [50]:
data[names == "Charles", :]

array([[ 1.74380953,  0.41075475, -0.36585318,  0.61616358],
       [ 2.14664601, -0.4652285 , -1.09416193, -0.52367773]])

In [51]:
data[names == "Kilho", :]

array([[ 0.33475303, -0.22886941, -1.97264993, -1.32430933],
       [-0.10149452, -0.80051021,  0.96158134,  2.46254377],
       [ 1.83083561,  0.17823193, -0.07065599,  0.6681713 ]])

In [52]:
data[(names == "Charles") | (names == "Kilho"), :]

array([[ 1.74380953,  0.41075475, -0.36585318,  0.61616358],
       [ 0.33475303, -0.22886941, -1.97264993, -1.32430933],
       [ 2.14664601, -0.4652285 , -1.09416193, -0.52367773],
       [-0.10149452, -0.80051021,  0.96158134,  2.46254377],
       [ 1.83083561,  0.17823193, -0.07065599,  0.6681713 ]])

In [53]:
data[:,3]

array([ 0.61616358, -1.32430933, -0.97749358, -0.52367773, -0.57015537,
        2.46254377,  0.6681713 ])

In [54]:
data[:, 3] < 0

array([False,  True,  True,  True,  True, False, False])

In [55]:
data[data[:,3] < 0, :]

array([[ 0.33475303, -0.22886941, -1.97264993, -1.32430933],
       [-1.7020177 , -0.09785498, -1.79617633, -0.97749358],
       [ 2.14664601, -0.4652285 , -1.09416193, -0.52367773],
       [-1.01999619, -0.59397758,  0.25072865, -0.57015537]])

In [56]:
data[data[:,3] < 0, 0:2] = 0
data

array([[ 1.74380953,  0.41075475, -0.36585318,  0.61616358],
       [ 0.        ,  0.        , -1.97264993, -1.32430933],
       [ 0.        ,  0.        , -1.79617633, -0.97749358],
       [ 0.        ,  0.        , -1.09416193, -0.52367773],
       [ 0.        ,  0.        ,  0.25072865, -0.57015537],
       [-0.10149452, -0.80051021,  0.96158134,  2.46254377],
       [ 1.83083561,  0.17823193, -0.07065599,  0.6681713 ]])