In [1]:
import numpy as np

In [7]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 제곱근 sqrt

In [8]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

### log10

In [9]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [23]:
x = np.random.randn(10)
y = np.random.randn(10)

print(x, '\n\n', y)

[ 0.41856468  0.4448608  -0.65051133  0.03931299  1.15313971  1.05131451
 -1.67822471 -0.54932284 -0.1761723  -1.06394097] 

 [ 0.16302398 -1.17110626  1.56162789 -0.23780442 -1.31545227 -0.24832123
  0.01430212 -0.40029209 -1.52075195  0.15939942]


### Maximum, Max

In [24]:
# Maximum 함수는 두 array의 길이가 동일해야함 (강의와 버전 다름)
np.maximum(x, y)

array([ 0.41856468,  0.4448608 ,  1.56162789,  0.03931299,  1.15313971,
        1.05131451,  0.01430212, -0.40029209, -0.1761723 ,  0.15939942])

In [25]:
np.max(y)

1.5616278908485914

### array 통계값

In [28]:
arr = np.random.randn(5, 4)
arr

array([[ 0.43090046, -0.37098124, -0.92174261, -0.55598116],
       [-0.06741704, -1.03482848,  0.05032721,  0.95590412],
       [-1.55288467,  0.52437923,  1.18261715,  0.00492187],
       [ 1.3843389 ,  1.80945691, -0.55932371,  1.5257406 ],
       [-0.93083435,  0.292174  , -0.8823092 , -1.39188735]])

In [29]:
arr.sum()

-0.10742937204703695

In [30]:
arr.mean()

-0.005371468602351848

### 각 열(axis=0) 및 행(axis=1)에 대한 통계값

In [31]:
arr.sum(axis=0)

array([-0.7358967 ,  1.22020041, -1.13043115,  0.53869807])

In [32]:
arr.sum(axis=1)

array([-1.41780455, -0.09601419,  0.15903358,  4.1602127 , -2.9128569 ])

In [33]:
arr[0].sum()

-1.4178045533684998

In [34]:
arr[0:2].sum()

-1.5138187479970755

### 특정조건 만족하는 (mask) 값들의 count

In [35]:
arr > 0

array([[ True, False, False, False],
       [False, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True, False,  True],
       [False,  True, False, False]])

In [36]:
arr.dtype

dtype('float64')

In [37]:
(arr > 0).sum()

10

### 상위 몇 %에 해당하는 값 추출

In [39]:
arr = np.random.rand(8)
arr

array([0.13668598, 0.03323128, 0.9508561 , 0.33286262, 0.66510289,
       0.78024274, 0.78601151, 0.29586406])

In [40]:
# 오름차순 정렬
np.sort(arr)

array([0.03323128, 0.13668598, 0.29586406, 0.33286262, 0.66510289,
       0.78024274, 0.78601151, 0.9508561 ])

In [42]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([0.9508561 , 0.78601151, 0.78024274, 0.66510289, 0.33286262,
       0.29586406, 0.13668598, 0.03323128])

In [43]:
arr = np.random.randn(5, 3)
arr

array([[ 0.12994117, -0.52337127, -0.74494609],
       [ 1.18718352,  0.02974543,  1.09281849],
       [-0.28958952,  2.33271422,  1.474792  ],
       [ 0.26864429, -1.57650311, -0.18434288],
       [ 1.21104145, -0.51288263,  1.16485104]])

In [46]:
# 각 열에 대하여 (행: axis=1) 오름차순 정렬
np.sort(arr, axis=0)

array([[-0.28958952, -1.57650311, -0.74494609],
       [ 0.12994117, -0.52337127, -0.18434288],
       [ 0.26864429, -0.51288263,  1.09281849],
       [ 1.18718352,  0.02974543,  1.16485104],
       [ 1.21104145,  2.33271422,  1.474792  ]])

In [47]:
large_arr = np.random.randn(150)
large_arr

array([ 4.61442473e-02,  1.67183953e-02,  1.47721207e+00,  3.76448141e-01,
       -2.92354073e-01, -8.39488473e-01, -3.21750122e-01, -1.36740127e-01,
        5.02454961e-01, -4.93852066e-01,  5.89254346e-01,  1.40280361e+00,
       -2.96889440e-01,  8.24466042e-01,  5.73996206e-01,  8.90525858e-01,
        3.32744032e-01,  5.13934730e-01,  1.18216317e+00, -1.34074596e+00,
       -4.33108986e-01,  8.85077196e-01,  5.66942162e-01,  5.26050727e-02,
       -1.66900308e+00,  1.48248300e+00, -9.67468720e-02,  8.26970233e-01,
        4.64669970e-01,  3.57784570e-01, -6.39780872e-01, -4.94178847e-01,
       -1.29157020e+00, -6.53880196e-01,  1.36881177e+00, -3.36379316e-01,
       -3.66058352e-01, -1.08099852e+00,  1.81770464e+00, -8.63577682e-01,
        9.68792354e-01, -3.22435109e-01, -3.52022936e-01, -1.14811701e+00,
        7.56333063e-01, -1.08145742e+00,  9.11538305e-02,  6.50783840e-01,
       -1.86374994e+00, -3.97864706e-02,  1.27768882e+00,  9.82630135e-02,
       -1.16775062e-01, -

In [56]:
np.sort(large_arr)[::-1][0:int(0.05 * len(large_arr))]

array([2.13116934, 1.81770464, 1.74027481, 1.72026189, 1.69272017,
       1.518941  , 1.49996924])

### Unique 함수

In [53]:
names = np.array(["Charles", "Kilho", "Hayoung", "Charles", "Hayoung", "Kilho", "Kilho"])
ints  = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])                  

In [54]:
np.unique(names)

array(['Charles', 'Hayoung', 'Kilho'], dtype='<U7')

In [55]:
np.unique(ints)

array([1, 2, 3, 4])